zookeeper:
  address: ${zookeeper.address}

#endpoints关闭，可以防止泄露密码
#endpoints:
#  enabled: ${endpointsEnabled}

#security打开，health健康检查端口可以使用，sporing boot admin 可以用。关闭状态容易泄露信息
management:
  security:
    enabled: ${securityEnabled}

coros:
  email:
    systemEmail: coros@sysmessage.coros.com
  checkCode:
    requestCount: 20
    ipRequestCount: 100
  sport:
    #运动数据缩率图最大不能超过200kb,单个文件
    imageMaxSize: 204800
    #运动详情文件最大不能超过2mb,单个文件
    dataMaxSize: 2097152
  maxTimezone: 96
  messageFileMaxSize: 2097152
  #轨迹文件大小不能超过1Mb，单个文件
  trackFileMaxSize: 1048576
  helmetFirmwareTypeList: COROS HA05,COROS HA06,COROS HA07
  helmetsStartFirmwareVersion: 2.0.0.0
  elevationCalibrationArea: ${elevationCalibrationArea}
  autoFeedbackInterval: 24

server:
  port: ${httpPort}
  context-path: /coros
  #  connectionTimeout: 60000
  tomcat:
    uri-encoding: UTF-8
    basedir: ${tomcat.basedir}
    accesslog:
      enabled: true
      #请求真实IP、远程主机IP、本机IP、远程用户名、访问日期和时间（响应时间，结束时间点）、 HTTP请求中的第一行、发送字节数（响应字节数，返回的Response字节数）、状态码、耗时毫秒、协议、请求方式、查询串、请求的URL路径、耗时秒
      pattern: '%{X-Forwarded-For}i %a %A %l %{yyyy-MM-dd HH:mm:ss.SSS}t "%r" %b(byte) %s %D(ms)  %H %m %q %U %T'

spring:
  boot:
    admin:
      url: http://${spring.boot.admin.server.ip}:9999
      username: admin       #These two are needed so that the client
      password: 123456   #can register at the protected server api
  http:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      location: ${spring.http.multipart.localtion}
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  application:
    name: @project.artifactId@
  kafka:
    producer:
      bootstrap-servers: ${kafka.bootstrap.server}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 3


#固件存放在oss上面
firmware:
  #固件压缩文件不能超过10mb
  fileMaxSize: 10485760

#头像文件放在oss上面去
avatar:
  #头像文件不能超过5mb
  fileMaxSize: 5242880


# 日志文件路径
logging:
  config: ${logConfig}

#主键生成器配置信息
primaryKey:
  #序列号占14位
  sequenceBit: 14
  # 模块号占7位
  modeBit: 7
  # 机器码或者服务实例编号占7位
  workeridBit: 7
  # 机器码或者服务实例编号
  workerid: ${workerid}

#打包类型，1：现场正式环境，2：测试环境，3：开发环境
deployType: ${deployType}

region:
  name: ${region.name}
  enableCrossRegionCheck: ${region.enableCrossRegionCheck}
  crossRegionResetPasswordUrl: ${region.crossRegionResetPasswordUrl}

bigdata:
  product:
    name: coros
  activeMsg:
    enabled: ${bigdata.activeMsg.enabled}
    topic:
      name: bd-activeMsg
  deviceInfo:
    enabled: ${bigdata.deviceInfo.enabled}
    topic:
      name: bd-deviceInfo